### PR TITLE
feat: switch to multicall3

### PR DESCRIPTION
**Pull request by mds1**
Closes https://github.com/joshstevens19/ethereum-multicall/issues/45

I didn't update the ABI to include the new Multicall3 methods since it's not deployed on etherlite. I confirmed it built successfully, but I didn't see any tests so I'm not sure how to verify I didn't break anything 😅

All chains are still present and many new ones added, but the sort order is now based on that of the Multicall3 readme so the diff is a bit wonky.

### CODE REVIEW

**Comment by joshstevens19** [comment]
Thanks for this.. Haha yep sorry > https://github.com/joshstevens19/ethereum-multicall/issues/1 I did this repo a while ago and never had or should I say made time to add tests.. but I can easily do an E2E test il fetch and test this out over weekend thanks for doing it! 

one thing could you update the readme supported chains ?

**Comment by mds1** [comment]
README updated!

**Review by joshstevens19 — APPROVED** [review]
approved pending manual test over weekend thanks again @mds1

**Comment by joshstevens19** [comment]
this is now deployed thanks a lot

**Comment by mds1** [comment]
Awesome, thank you! 🙌

**Pull request merged**
