### PR TITLE
fix-exception

### PR DESCRIPTION
**Pull request by Yohox**

### CODE REVIEW

**Comment by Yohox** [comment]
In some case defaultAbiCoder.decode will throw exception even if set the tryAggregate

**Comment by joshstevens19** [comment]
Hey thanks for PR! Have you got an example of a broken one I can test it with?

**Comment by Yohox** [comment]
here is a example: https://github.com/Yohox/multicall-exception
when invoke a contract but address is not a contract address or correct address it will throw exception which even if set tryAggregate true

**Comment by joshstevens19** [comment]
Thanks a lot will test and look tomorrow

**Review by joshstevens19 — APPROVED** [review]

**Pull request merged**
