### PR TITLE
fixing blocknumber issue

### PR DESCRIPTION
**Pull request by HadiEsna**
#99

### CODE REVIEW

**Comment by HadiEsna** [comment]
Hi @joshstevens19 
Can you review this PR?

**Comment by joshstevens19** [comment]
Thanks for the PR - have you tested this out? can you add a description in this also

**Comment by HadiEsna** [comment]
yes I've tested it on all evm chains (We are getting historical data for multiple protocols and I've used it for that)

**Comment by HadiEsna** [comment]
Issue:
The blocknumber in the call wasn't changing the block number that the request was executing. After some digging, I noticed that the implementation of calling the multicall contract on an specific block is not correct.

```
 const callParams = [];
 callParams.push(options.blockNumber);
 const contractResponse = (await contract.methods
        .aggregate(this.mapCallContextToMatchContractFormat(calls))
        .call(...callParams)) as AggregateContractResponse;
```

After I changed it to this, it worked normally 
```
const contractResponse = (await contract.methods
        .aggregate(this.mapCallContextToMatchContractFormat(calls))
        .call(...callParams)) as AggregateContractResponse;
        .call({}, blockNumber)) as AggregateContractResponse;
```

**Comment by HadiEsna** [comment]
@joshstevens19 Can you check this PR please?
Is there anything else that I need to add?

**Comment by joshstevens19** [comment]
sorry for delay merged - https://github.com/joshstevens19/ethereum-multicall/releases/tag/2.26.0

**Pull request merged**
