### PR TITLE
Fix finding the output types from abi definition

### PR DESCRIPTION
**Pull request by jsertx**
If we have in the abi several methods with different inputs we aren't going to just put the method name but the signature, to allow the ethers package distinguise which one is using. So I am extending it to find AbiItem when a method signature is given.

### CODE REVIEW

**Comment by joshstevens19** [comment]
Thanks for PR! This makes sense could you add a section in the docs about this just a little bit explaining when people can use this over a name..

**Comment by joshstevens19** [comment]
MethodName passed by the user though right? (Looking at this through phone) People may not know that they can pass in the signature instead in that parameter or even know the ABI has mapped that, I know most may but anything we can clear up would be great. If you think no docs needed no worries.

Basically if the user doesn’t need to care no docs but if the user could get confused a few lines go along way! Thanks dude!

**Comment by jsertx** [comment]
I have added some docs on the README.MD! with a real example too.
Also, I have done a refactor so instead of constructing the signature ourselves, we are using the ethers package so we do not need to mantain signature building changes and just keep updated the ethers library.

**Comment by joshstevens19** [comment]
Looks good nice work merging deploy tomorrow! 👍👍

**Review by joshstevens19 — APPROVED** [review]

**Comment by joshstevens19** [comment]
deployed

**Pull request merged**
